const LOAD_PRODUCTS_SEARCH_RESULTS = 'LOAD_PRODUCTS_SEARCH_RESULTS';
const LOAD_USER_DATA = 'LOAD_USER_DATA';
const LOAD_SALES_DATA = 'LOAD_SALES_DATA';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOAD_CUSTOMERS_DATA = 'LOAD_CUSTOMERS_DATA';
const LOAD_TOP_PRODUCTS_DATA = 'LOAD_TOP_PRODUCTS_DATA';
const LOAD_TRANSACTIONS_DATA = 'LOAD_TRANSACTIONS_DATA';

export {
  LOAD_PRODUCTS_SEARCH_RESULTS,
  LOAD_USER_DATA,
  LOAD_SALES_DATA,
  TOGGLE_SIDEBAR,
  LOAD_CUSTOMERS_DATA,
  LOAD_TOP_PRODUCTS_DATA,
  LOAD_TRANSACTIONS_DATA,
};
