export const LOAD_PRODUCTS_SEARCH_RESULTS = 'LOAD_PRODUCTS_SEARCH_RESULTS';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const LOAD_SALES_DATA = 'LOAD_SALES_DATA';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOAD_CUSTOMERS_DATA = 'LOAD_CUSTOMERS_DATA';
export const LOAD_TOP_PRODUCTS_DATA = 'LOAD_TOP_PRODUCTS_DATA';
