const CONSTANTS = {
  DEBOUNCE_DELAY: 1000,
  NAVBAR_HEIGHT_MOBILE: 56,
  NAVBAR_HEIGHT_DESKTOP: 65,
  SIDEBAR_WIDTH: 250,
  SIDEBAR_LIST_ITEM_WIDTH: 218,
  SIDEBAR_SCROLLBAR_WIDTH: 5,
  IMAGE_LIST_GAP: 25,
  IMAGE_LIST_ROW1_HEIGHT: 198,
  IMAGE_LIST_ROW2_HEIGHT: 243,
};

export default CONSTANTS;
