const CONSTANTS = {
  DEBOUNCE_DELAY: 1000,
  NAVBAR_HEIGHT_MOBILE: 56,
  NAVBAR_HEIGHT_DESKTOP: 65,

  SIDEBAR_WIDTH: 250,
  SIDEBAR_LIST_ITEM_WIDTH: 218,
  SIDEBAR_SCROLLBAR_WIDTH: 5,

  IMAGE_LIST_GAP: 45,
  IMAGE_LIST_ROW1_HEIGHT: 198,
  IMAGE_LIST_ROW2_HEIGHT: 243,

  GRAPH_RESPONSIVE_CONTAINER_HEIGHT: 420,
  TICK_FONT_SIZE: 13,
  ROTATE_TICK_BY_ANGLE: -45,
  TOOLTIP_POSITION_X_COORIDANTE: -70,
  TOOLTIP_POSITION_Y_COORIDANTE: -120,
  ACTIVE_DOT_RADIUS: 8,
  ACTIVE_DOT_BORDER: 3,
  HORIZONTAL_DISTANCE_OF_YTICKS_FROM_AXIS: -10,
  HORIZONTAL_DISTANCE_OF_XTICKS_FROM_AXIS_MOBILE: -15,
  HORIZONTAL_DISTANCE_OF_XTICKS_FROM_AXIS_DESKTOP: 3,
  VERTICAL_DISTANCE_OF_XTICKS_FROM_AXIS_MOBILE: 40,
  VERTICAL_DISTANCE_OF_XTICKS_FROM_AXIS_DESKTOP: 25,
  X_AXIS_HEIGHT_MOBILE: 100,
  X_AXIS_HEIGHT_DESKTOP: 50,

  TABLE_MAXHEIGHT: 455,
  TABLE_MAXWIDTH: 957,

  TRANSACTIONS: {
    RECEIVE: 'receive',
    PROCESSING: 'processing',
    FAILED: 'failed',
    REFUND: 'refund',
    COMPLETED: 'completed',
    IN_PROGRESS: 'in progress',
    CANCELLED: 'cancelled',
    AMOUNT: 'amount',
    STATUS: 'status',
  },
};

export default CONSTANTS;
