export const URLS = {
  DASHBOARD: '/',
  AUTH: '/auth',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  LOGOUT: '/logout',
  HOME: '/home',
  ABOUT_US: '/aboutus',
  CONTACT_US: '/contactus',
  PRODUCT_LIST: '/productlist',
  BILLING: '/billing',
  INVOICE: '/invoice',
  MESSAGES: '/messages',
  ACCOUNT: '/account',
  LOGIN: '/login',
  SIGNIN: '/signin',
  DOCS: '/docs',
  COMPONENTS: '/components',
  HELP: '/help',
  ADJUSTMENTS: '/adjustments',
  GLOBE: '/globe',
  COG: '/cog',
};

export const NOT_FOUND = '*';
