import { Box } from '@mui/material';

import Footer from '@containers/Footer';

const MainContent = () => {
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column' }}>
      <h1>Main Overview</h1>
      <Box>
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
        ASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK
        DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP
        WERTYUIOJHGFDXCVNB SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMVASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMVASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMVVASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV
        SDFGHJKJHGFDFBNMASDFGHJKLWERTYUIOPXCVBNMERTYUIOP WERTYUIOJHGFDXCVNB
        SDFGHLKJHGFGHJK DFGHJKKHGFDFGHJNBVCV SDFGHJKJHGFDFBNM
      </Box>
      <Footer />
    </Box>
  );
};

export default MainContent;
